// PATH: lib/shell/utils.ts
// NO React imports — safe to use in server components too
import type { Activity, DailyMetrics, TrainingMetrics } from "@/lib/types";

// ─── UTILS ───────────────────────────────────────────────────────────────────

export function calcTM(acts:Activity[]):TrainingMetrics{if(!acts.length)return{ctl:0,atl:0,tsb:0,weekly_tss:0};const sorted=[...acts].sort((a,b)=>a.date.localeCompare(b.date));let ctl=0,atl=0;const kC=1-Math.exp(-1/42),kA=1-Math.exp(-1/7);for(const a of sorted){const t=a.tss??0;ctl=ctl+kC*(t-ctl);atl=atl+kA*(t-atl);}const wTss=acts.filter(a=>new Date(a.date)>=new Date(Date.now()-7*86400000)).reduce((s,a)=>s+(a.tss??0),0);return{ctl:Math.round(ctl),atl:Math.round(atl),tsb:Math.round(ctl-atl),weekly_tss:wTss};}
export function buildFitnessChart(acts:Activity[]){const W:Record<string,number[]>={};for(const a of acts){const d=new Date(a.date),m=new Date(d);m.setDate(d.getDate()-d.getDay()+1);const k=m.toISOString().split("T")[0];if(!W[k])W[k]=[];W[k].push(a.tss??0);}let ctl=0,atl=0;const kC=1-Math.exp(-1/42),kA=1-Math.exp(-1/7);return Object.keys(W).sort().slice(-12).map((w,i)=>{const t=W[w].reduce((s,v)=>s+v,0);ctl=ctl+kC*(t-ctl);atl=atl+kA*(t-atl);return{week:`W${i+1}`,ctl:Math.round(ctl),atl:Math.round(atl),tsb:Math.round(ctl-atl)};});}
export function buildWeekBar(acts:Activity[]){const days=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],now=new Date();return days.map((day,i)=>{const d=new Date(now);d.setDate(now.getDate()-(now.getDay()||7)+1+i);return{day,tss:acts.filter(a=>a.date===d.toISOString().split("T")[0]).reduce((s,a)=>s+(a.tss??0),0)};});}
export function buildPaceTrend(acts:Activity[]){return acts.filter(a=>a.sport==="running"&&a.avg_pace_sec_km).slice(0,8).reverse().map((a,i)=>({label:`S${i+1}`,pace:parseFloat((a.avg_pace_sec_km!/60).toFixed(2))}));}
export function buildRadar(acts:Activity[]){const r=acts.filter(a=>a.sport==="running").length,c=acts.filter(a=>a.sport==="cycling").length,sw=acts.filter(a=>a.sport==="swimming").length,st=acts.filter(a=>a.sport==="strength").length,tss=acts.reduce((s,a)=>s+(a.tss??0),0);return[{attr:"Endurance",val:Math.min(100,Math.round(tss/10))},{attr:"Threshold",val:Math.min(100,r*8+20)},{attr:"VO2Max",val:Math.min(100,c*6+30)},{attr:"Speed",val:Math.min(100,r*5+15)},{attr:"Strength",val:Math.min(100,st*12+20)},{attr:"Technique",val:Math.min(100,sw*10+30)}];}
export function buildWeekly(acts:Activity[]){const W:Record<string,Activity[]>={};for(const a of acts){const d=new Date(a.date),m=new Date(d);m.setDate(d.getDate()-d.getDay()+1);const k=m.toISOString().split("T")[0];if(!W[k])W[k]=[];W[k].push(a);}return Object.entries(W).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,8).map(([k,aa])=>{let dayMask=0;aa.forEach(a=>{const dow=(new Date(a.date).getDay()+6)%7;dayMask|=(1<<dow);});return{label:new Date(k).toLocaleDateString("en",{month:"short",day:"numeric"}),volume:(()=>{const km=aa.reduce((s,a)=>s+(a.distance_meters??0)/1000,0);return km>0?`${km.toFixed(0)} km`:"—";})(),tss:aa.reduce((s,a)=>s+(a.tss??0),0),sessions:aa.length,avgHR:(()=>{const h=aa.filter(a=>a.avg_heart_rate);return h.length?`${Math.round(h.reduce((s,a)=>s+(a.avg_heart_rate??0),0)/h.length)} bpm`:"—";})(),feel:(()=>{const f=aa.filter(a=>a.feel_score);return f.length?`★${(f.reduce((s,a)=>s+(a.feel_score??0),0)/f.length).toFixed(1)}`:"—";})(),dayMask};})}
export function buildTSSChart(acts:Activity[],weeks:number){const W:Record<string,number>={};for(const a of acts){const d=new Date(a.date),m=new Date(d);m.setDate(d.getDate()-d.getDay()+1);const k=m.toISOString().split("T")[0];W[k]=(W[k]??0)+(a.tss??0);}return Object.entries(W).sort((a,b)=>a[0].localeCompare(b[0])).slice(-weeks).map(([,tss],i)=>({week:`W${i+1}`,tss:Math.round(tss)}));}
export function calcRec(m:DailyMetrics){const sleep=m.sleep_hours??7,hrv=m.hrv_ms??55,fatigue=m.fatigue??5,mot=m.motivation??7;return Math.round(Math.min(100,(sleep/8)*40+Math.min(100,(hrv/70)*30)+Math.max(0,(1-fatigue/10)*20)+(mot/10)*10));}
export function getAutoInsight(m:DailyMetrics){const h=m.hrv_ms??0,sl=m.sleep_hours??0,f=m.fatigue??5;if(h>=65&&sl>=7.5&&f<=4)return"Excellent recovery";if(h>=50&&sl>=6.5&&f<=6)return"Moderate recovery";return"Low recovery — rest";}
export function fmtDuration(s:number|null){if(!s)return"—";const h=Math.floor(s/3600),m=Math.floor((s%3600)/60);return h>0?`${h}h ${m}m`:`${m} min`;}
export function fmtDist(m:number|null,sport:string){if(!m)return"—";return sport==="swimming"?`${m.toFixed(0)} m`:`${(m/1000).toFixed(1)} km`;}
export function fmtPace(s:number){return`${Math.floor(s/60)}:${String(Math.round(s%60)).padStart(2,"0")}`;}
export function fmtDate(d:Date){return d.toLocaleDateString("en",{weekday:"long",year:"numeric",month:"long",day:"numeric"}).toUpperCase();}
export function formatRelDate(ds:string){const d=Math.floor((Date.now()-new Date(ds).getTime())/86400000);return d===0?"today":d===1?"yesterday":d<7?`${d}d ago`:new Date(ds).toLocaleDateString("en",{month:"short",day:"numeric"});}
export function getGreeting(){const h=new Date().getHours();return h<12?"Good morning":h<18?"Good afternoon":"Good evening";}
export function getWeekN(){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()+4-(d.getDay()||7));return Math.ceil(((d.getTime()-new Date(d.getFullYear(),0,1).getTime())/86400000+1)/7);}